# original_multiCS_extinction_3x10.toml
include = "common.toml"

enabled_features = ["base", "extinction"]

[base.cs]
maxNumConflicts        = 10
limitParentsToResolved = true

[extinction]
extinctAfterXTimesNoConflict = 3
stopAfterXExtinctions        = 10
