# weighting_full_extinction_3x10.toml
include = "common.toml"

enabled_features = ["base", "weighting", "extinction"]

[base.cs]
maxNumConflicts        = 10
limitParentsToResolved = false

[extinction]
extinctAfterXTimesNoConflict = 3
stopAfterXExtinctions        = 10

[weighting]
weightedConflicts         = true
avoidSameOriginalConflict = true
weightedCrossover         = true
weightedCrossoverFactor   = 2